service: products-service
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-west-1

plugins:
  - serverless-bundle

functions:
  post-products:
    handler: src/functions/products.createProduct
    events:
      - http:
          path: products
          method: post
          cors: true

  get-products:
    handler: src/functions/products.getProductsList
    events:
      - http:
          path: products
          method: get

  get-product:
    handler: src/functions/product.getProductById
    events:
      - http:
          path: products/{id}
          method: get
          request:
            parameters:
              paths:
                id: true

custom:
  documentation:
    version: '1'
    title: 'My API'
    description: 'This is my API'
    models: { }
  bundle:
    ignorePackages:
      - pg-native

