service: products-service
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-west-1

  environment:
    SNS_ARN:
      Fn::ImportValue: SNSPotatoesTopicARN

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sns:*"
      Resource:
        Fn::ImportValue: SNSPotatoesTopicARN

plugins:
  - serverless-bundle

functions:
  catalog-batch:
    handler: src/functions/catalog.catalogBatchProcess
    environment:
      SNS_ARN:
        Fn::ImportValue: SNSPotatoesTopicARN
    events:
      - sqs:
          maximumBatchingWindow: 10
          batchSize: 5
          arn:
            Fn::ImportValue: SQSPotatoesARN

  post-products:
    handler: src/functions/products.createProduct
    events:
      - http:
          path: products
          method: post
          cors: true

  get-products:
    handler: src/functions/products.getProductsList
    events:
      - http:
          path: products
          method: get
          cors: true

  get-product:
    handler: src/functions/product.getProductById
    events:
      - http:
          path: products/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true

custom:
  documentation:
    version: '1'
    title: 'My API'
    description: 'This is my API'
    models: { }
  bundle:
    ignorePackages:
      - pg-native

