service: import-service
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-west-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::potatoes-uploads/uploads"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::potatoes-uploads/uploads/*"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::potatoes-uploads/parsed/*"

plugins:
  - serverless-bundle

functions:
  import-products:
    handler: src/functions/products.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true

  import-parser:
    handler: src/functions/parser.importFileParser
    events:
      - s3:
          bucket: potatoes-uploads
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
          existing: true

custom:
  documentation:
    version: '1'
    title: 'My API'
    description: 'This is my API'
    models: { }

